# Generated by Django 3.0.2 on 2020-02-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('empployee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('disignation', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
