# Generated by Django 3.0.2 on 2020-02-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_reqmodel',
            name='contact_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='new_reqmodel',
            name='department_id',
            field=models.IntegerField(unique=True),
        ),
    ]
