# Generated by Django 3.0.2 on 2020-02-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationmodel',
            old_name='contact_no',
            new_name='mobaile_no',
        ),
    ]
