# Generated by Django 3.0.2 on 2020-02-29 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_auto_20200301_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationmodel',
            old_name='adress',
            new_name='address',
        ),
    ]
