# Generated by Django 3.0.2 on 2020-02-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_auto_20200301_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
