# Generated by Django 3.0.2 on 2020-03-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_auto_20200301_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationformModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Date_of_birth', models.DateField()),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('percentage', models.FloatField()),
                ('upload_resume', models.FileField(upload_to='applicationresumes/')),
            ],
        ),
    ]
